server:
  port: 8080

spring:
  application:
    name: MentorMatch
  datasource:
    url: jdbc:mysql://localhost:3306/mentormatch_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Darlingofme # Replace with your local mysql password if necessary
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

app:

  jwt:
    secret: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b" # At least 256-bit key for HMAC-SHA256
    expiration: 3600000  #1 hours in milliseconds
  
  cloudinary:
    cloud_name: dhz3ngdeg # Replace with your Cloudinary cloud name
    api_key: 416376455625773 # Replace with your Cloudinary API key
    api_secret: 1ALNNm10-bDmv41SFM_20J-5H3A # Replace with your Cloudinary API secret
vnpay:
    tmnCode: "PIUY8BWH"
    secretKey: "LZFA9YCG9QU9LMD31GGQ98UA2JWJD0X9"
    vnp_PayUrl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    returnUrl: "http://localhost:8080/api/payment/vnpay-return" 
